In [1]:
import numpy as np

In [7]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])

In [8]:
a.shape

(2, 4)

In [11]:
np.zeros([2,4],dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.ones([3,3],dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.full([3,5],6.8)

array([[6.8, 6.8, 6.8, 6.8, 6.8],
       [6.8, 6.8, 6.8, 6.8, 6.8],
       [6.8, 6.8, 6.8, 6.8, 6.8]])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
x1 = np.random.randint(20,size = 6)
x1

array([ 5,  6, 17, 16,  5, 10])

In [22]:
x2 = np.random.randint(20,size = (3,4))
x2

array([[18, 12,  9,  7],
       [ 8,  7, 16,  0],
       [11, 17,  0, 18]])

In [25]:
x2[:,:2]

array([[18, 12],
       [ 8,  7],
       [11, 17]])

In [33]:
grid = np.arange(1,10)
print(grid)
grid.shape

[1 2 3 4 5 6 7 8 9]


(9,)

In [31]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
x = np.array([[1.,2.],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [35]:
x.T

array([[1., 3.],
       [2., 4.]])

In [37]:
x = np.array([1,2,3])
y = np.array([3,2,1])


In [38]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [39]:
test = np.array([[1,2,3],
                 [4,5,6]])
test

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.concatenate((test,test))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
np.concatenate((test,test),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [50]:
a = np.ones((3,2),dtype = int)
a

array([[1, 1],
       [1, 1],
       [1, 1]])

In [51]:
a + 3

array([[4, 4],
       [4, 4],
       [4, 4]])

In [ ]:
nhathai = np.random.random(10000)

In [54]:
dog_hight = [600,470,170,430,300]
dog_hight = np.array(dog_hight)
np.std(dog_hight) # tinh do lech chuan cua du lieu

147.32277488562318

In [55]:
np.var(dog_hight) # tinh phuong sai cua du lieu

21704.0

In [57]:
np.random.seed(42)
MatA = np.random.randint(0,10,size = (4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [58]:
np.sort(MatA,axis = 0 ) # sort column

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [59]:
np.sort(MatA,axis = 1) # sort row

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [62]:
np.random.seed(0)
sales_amounts = np.random.randint(20,size = (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [64]:
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index = ["Monday","Tuesday","Wednesday","Thursday","Friday"], 
                            columns = ["Almond butter","Peanute buuter","Cashwew butter"])
weekly_sales

Almond butter  Peanute buuter  Cashwew butter
Monday                12              15               0
Tuesday                3               3               7
Wednesday              9              19              18
Thursday               4               6              12
Friday                 1               6               7

In [65]:
prices = np.array([10,8,12])

butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"], columns = ["Almond butter","Peanute buuter","Cashwew butter"])
butter_prices

Almond butter  Peanute buuter  Cashwew butter
Price             10               8              12

In [66]:
total_prices = weekly_sales.dot(butter_prices.T)
total_prices 

Price
Monday       240
Tuesday      138
Wednesday    458
Thursday     232
Friday       142

In [67]:
weekly_sales["Total price"] = total_prices
weekly_sales

Almond butter  Peanute buuter  Cashwew butter  Total price
Monday                12              15               0          240
Tuesday                3               3               7          138
Wednesday              9              19              18          458
Thursday               4               6              12          232
Friday                 1               6               7          142